//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tele3.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user32_dbEntities2 : DbContext
    {
        public user32_dbEntities2()
            : base("name=user32_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tele3_Clients> Tele3_Clients { get; set; }
        public virtual DbSet<Tele3_Numbers> Tele3_Numbers { get; set; }
        public virtual DbSet<Tele3_Orders> Tele3_Orders { get; set; }
        public virtual DbSet<Tele3_Tarifs> Tele3_Tarifs { get; set; }
    }
}
