//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tele3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tele3_Orders
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surmane { get; set; }
        public string secondname { get; set; }
        public System.DateTime date { get; set; }
    }
}
