//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tele3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tele3_Tarifs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tele3_Tarifs()
        {
            this.Tele3_Numbers = new HashSet<Tele3_Numbers>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int cost { get; set; }
        public int minutes { get; set; }
        public string internet { get; set; }
        public string messages { get; set; }
        public string about { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tele3_Numbers> Tele3_Numbers { get; set; }
    }
}
